### ISSUE TITLE
2 TableView in ScrollView 

### ISSUE THREAD

**Issue by Michaelsafir** [muukii/Rideau#11]
Good Day, i found some bug or feature. If i put scroll view in Rideau - all works fine. When i scroll my vie on top Rideau makes smaller - it's cool. But! When i need to use 2 TableViews in ScrollView in Rideau and scroll one of TableViews on top - Rideau want to make view smaller. Can you make param that will detect nesting of 2 scrolls in Rideau and don't close my window until i scroll my first view on top. Actually your framework is awesome!

![image](https://user-images.githubusercontent.com/33763394/55397541-226f2f00-554f-11e9-91f0-b27fa408f5f6.png)

**Comment by JohnEstropia** [comment]
@Michaelsafir Have you tried to set the `rideauView.trackingScrollViewOption` to `.specific(topScrollView)`?

**Comment by Michaelsafir** [comment]
> @Michaelsafir Have you tried to set the `rideauView.trackingScrollViewOption` to `.specific(topScrollView)`?

That's works, really fine! Thank you!

**Comment by JohnEstropia** [comment]
That’s great :)

Closing this issue now but feel free to comment if there are further issues.
