### ISSUE TITLE
Apps using Rideau framework are rejected by apple

### ISSUE THREAD

**Issue by buechner** [muukii/Rideau#36]
Apple rejects my app right after uploading it with the following e-mail:

We identified one or more issues with a recent delivery for your app, "TheApp" 1.0 (1). Please correct the following issues, then upload again.

ITMS-90511: CFBundleIdentifier Collision - The Info.plist CFBundleIdentifier value 'me.muukii.Cabinet' of 'TheApp.app/Frameworks/Rideau.framework' is already in use by another application.

I did some research and found that the framework target may use the wrong info.plist file (the one from the demo).

**Comment by JohnEstropia** [comment]
You might have added the Demo app accidentally to your project. Please use Cocoapods or Carthage to use the framework as the main project is not meant to be imported as-is.

**Comment by buechner** [comment]
I created a pull request https://github.com/muukii/Rideau/pull/37
